# Generated by Django 5.2.7 on 2025-11-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='critical_priority_avaiable_beds',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
