# Generated by Django 5.2.7 on 2025-11-02 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_emargency_contact_patient_emergency_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disaster_zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('demand', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Supply_center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TransportFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_sent', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.supply_center')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.disaster_zone')),
            ],
        ),
    ]
