# Generated by Django 5.2.7 on 2025-11-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_transportflow_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportflow',
            name='send_limits',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
