# Generated by Django 5.2.7 on 2025-11-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_transportflow_send_limits'),
    ]

    operations = [
        migrations.CreateModel(
            name='supply_max_cap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_capacity', models.IntegerField(default=100)),
            ],
        ),
    ]
