# Generated by Django 5.2.7 on 2025-11-02 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_supply_max_cap'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='quantity',
            new_name='volume',
        ),
    ]
