# Generated by Django 5.2.7 on 2025-11-02 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_hospitaltransfer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='emargency_contact',
            new_name='emergency_contact',
        ),
    ]
