# Generated by Django 5.2.7 on 2025-11-02 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_disaster_zone_supply_center_transportflow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportflow',
            name='timestamp',
        ),
    ]
