# Generated by Django 5.2.8 on 2025-11-11 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_quantity_resource_volume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportflow',
            name='zone',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.RemoveField(
            model_name='hospitaltransfer',
            name='to_hospital',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='hospital_name',
        ),
        migrations.RemoveField(
            model_name='hospitaltransfer',
            name='from_hospital',
        ),
        migrations.RemoveField(
            model_name='transportflow',
            name='center',
        ),
        migrations.RenameField(
            model_name='transportflow',
            old_name='send_limits',
            new_name='max_capacity',
        ),
        migrations.RemoveField(
            model_name='supply_max_cap',
            name='max_capacity',
        ),
        migrations.AddField(
            model_name='resource',
            name='route_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supply_max_cap',
            name='capacity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supply_max_cap',
            name='name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transportflow',
            name='A',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transportflow',
            name='to',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Disaster_zone',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='Hospital',
        ),
        migrations.DeleteModel(
            name='HospitalTransfer',
        ),
        migrations.DeleteModel(
            name='Supply_center',
        ),
    ]
