# Generated by Django 5.2.8 on 2025-11-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_transportflow_zone_delete_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportflow',
            name='amount_sent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
