# Generated by Django 5.2.8 on 2025-11-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_transportflow_amount_sent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supply_max_cap',
            old_name='name',
            new_name='A',
        ),
        migrations.AddField(
            model_name='supply_max_cap',
            name='to',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
