# Generated by Django 5.2.8 on 2025-11-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_name_supply_max_cap_a_supply_max_cap_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='route_name',
        ),
        migrations.AddField(
            model_name='resource',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
